<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Payslip {{ $employee->employee_code }} {{ $month }}</title>
    <style>
        body { margin: 0; background: #f1f5f9; color: #0f172a; font-family: Arial, sans-serif; }
        .page { max-width: 760px; margin: 24px auto; background: #fff; padding: 36px; border-radius: 16px; box-shadow: 0 20px 45px rgba(15, 23, 42, .12); }
        .header { display: flex; justify-content: space-between; gap: 24px; border-bottom: 2px solid #10b981; padding-bottom: 18px; }
        h1 { margin: 0; font-size: 28px; }
        .muted { color: #64748b; font-size: 13px; }
        .net { margin: 24px 0; border-radius: 14px; background: #ecfdf5; padding: 22px; text-align: center; }
        .net strong { display: block; color: #059669; font-size: 36px; margin-top: 6px; }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
        .box { border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; }
        .row { display: flex; justify-content: space-between; border-bottom: 1px solid #f1f5f9; padding: 9px 0; font-size: 14px; }
        .row:last-child { border-bottom: 0; }
        .label { color: #64748b; }
        .total { font-weight: 700; }
        .footer { margin-top: 28px; border-top: 1px solid #e2e8f0; padding-top: 16px; color: #64748b; font-size: 12px; text-align: center; }
        @media print { body { background: #fff; } .page { margin: 0; box-shadow: none; border-radius: 0; } }
    </style>
</head>
<body>
<main class="page">
    <section class="header">
        <div>
            <h1>Shadow Group Payroll</h1>
            <div class="muted">Generated by Payroll System</div>
        </div>
        <div style="text-align:right">
            <strong>Payslip</strong>
            <div class="muted">{{ $month }}</div>
            <div class="muted">Status: {{ ucfirst($item->status) }}</div>
        </div>
    </section>

    <section class="grid" style="margin-top:22px">
        <div class="box">
            <div class="row"><span class="label">Employee</span><strong>{{ $employee->full_name }}</strong></div>
            <div class="row"><span class="label">Code</span><span>{{ $employee->employee_code }}</span></div>
            <div class="row"><span class="label">Department</span><span>{{ $employee->department?->name ?? '-' }}</span></div>
            <div class="row"><span class="label">Position</span><span>{{ $employee->position?->name ?? '-' }}</span></div>
        </div>
        <div class="box">
            <div class="row"><span class="label">Present</span><span>{{ $item->present_days }} days</span></div>
            <div class="row"><span class="label">Late</span><span>{{ $item->late_days }} days</span></div>
            <div class="row"><span class="label">Absent</span><span>{{ $item->absent_days }} days</span></div>
            <div class="row"><span class="label">Missing Checkout</span><span>{{ $item->missing_checkout_days }} days</span></div>
        </div>
    </section>

    <section class="net">
        Net Salary
        <strong>${{ number_format($item->net_salary, 2) }}</strong>
    </section>

    <section class="grid">
        <div class="box">
            <h3>Salary Breakdown</h3>
            <div class="row"><span class="label">Base Salary</span><span>${{ number_format($item->base_salary, 2) }}</span></div>
            <div class="row"><span class="label">Bonus</span><span>${{ number_format($item->bonus_amount, 2) }}</span></div>
            <div class="row"><span class="label">Commission</span><span>${{ number_format($item->commission_amount, 2) }}</span></div>
            <div class="row"><span class="label">Overtime</span><span>${{ number_format($item->overtime_amount, 2) }}</span></div>
        </div>
        <div class="box">
            <h3>Deductions</h3>
            <div class="row"><span class="label">Attendance Deductions</span><span>${{ number_format($item->deduction_amount, 2) }}</span></div>
            <div class="row"><span class="label">Salary Advance</span><span>${{ number_format($item->advance_amount, 2) }}</span></div>
            <div class="row total"><span>Total Deduction</span><span>${{ number_format($item->deduction_amount + $item->advance_amount, 2) }}</span></div>
        </div>
    </section>

    <section class="footer">
        Approval: {{ ucfirst($item->payroll->status) }} | Generated by Payroll System
    </section>
</main>
</body>
</html>
